### ISSUE TITLE
package not working

### ISSUE THREAD

**Issue by bbohling** [gajus/url-extractor#3]
Looks like there is an issue with the module...the JavaScript isn't present. You can test this yourself:

``` shell
npm install url-extractor
```

Noticed this when I came across [this issue](https://github.com/gajus/gitdown/issues/40) myself

**Comment by gajus** [comment]
Please provide code and the error that you are getting.

**Comment by bbohling** [comment]
Well, it is in the context of using **gitdown** (see [issue #40](https://github.com/gajus/gitdown/issues/40) ).

``` shell
🔥  $ ls
debugging.md node_modules package.json
~/Projects/Testing/gitdown
🔥  $ gitdown ./debugging.md --output-file ./debugging2.md
module.js:328
    throw err;
    ^

Error: Cannot find module 'url-extractor'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/bbohling/.nvm/versions/node/v4.2.6/lib/node_modules/gitdown/dist/gitdown.js:13:20)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/bbohling/.nvm/versions/node/v4.2.6/lib/node_modules/gitdown/dist/index.js:5:15)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at /Users/bbohling/.nvm/versions/node/v4.2.6/lib/node_modules/gitdown/dist/bin/index.js:74:19
    at Object.<anonymous> (/Users/bbohling/.nvm/versions/node/v4.2.6/lib/node_modules/gitdown/dist/bin/index.js:79:3)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
```

**Comment by gajus** [comment]
Tracking at https://github.com/gajus/gitdown/issues/40.
